### ISSUE TITLE
Make all features toggleable

### ISSUE THREAD

**Issue by TanvirOnGH** [TanvirOnGH/firefox-config#33]
### Description
Enhance the user chrome (`*css`) configuration by making all features toggleable using the `@supports -moz-bool-pref` directive. This will allow users to easily enable or disable specific customizations without modifying the CSS directly.

#### Example Implementation

Here's an example of how a feature can be made toggleable:

```css
@supports -moz-bool-pref("userchrome.horizontal-tab-bar-hidden.enabled") {
  #TabsToolbar {
    display: none !important;
  }
}
```

#### Benefits

- Reduces the need for users to edit the CSS file directly.
- Makes the configuration more modular and maintainable.
