### ISSUE TITLE
Implement Blurred Tabs Title in Sidebery

### ISSUE THREAD

**Issue by TanvirOnGH** [TanvirOnGH/firefox-config#67]
### Description

Implement a feature that blurs the tab titles in Sidebery to add a sleek aesthetic and to subtly obscure less active tabs. This will allow users to focus on the active tab while still being able to recognize other tabs in the background.

#### Example Implementation

Here's a conceptual example of how tab title blurring can be implemented using CSS:

```css
/* Blurred Tab text title */
.Tab .title {
  filter: blur(2px);
  transition: filter 0.3s ease;
}

.Tab.active .title {
  filter: none;
}
```

Examples by others: [r/FirefoxCSS custom search](https://www.reddit.com/r/FirefoxCSS/search/?q=blur+tab+title+sidebery&type=link), [Replicate the 'auto blur tab' feature from Waterfox in Firefox](https://www.reddit.com/r/FirefoxCSS/comments/1fs6iep/how_can_i_replicate_the_auto_blur_tab_feature/)

#### Benefits

- Enhances the visual appearance of the tab bar.
- Helps users focus on the active tab while maintaining visibility of others.
- Provides a clean, modern tab management experience.
