### ISSUE TITLE
Add Hover Highlight Effect for Active Tabs in Sidebery

### ISSUE THREAD

**Issue by TanvirOnGH** [TanvirOnGH/firefox-config#68]
### Description

Implement a hover highlight effect for active tabs in Sidebery to improve visual clarity. This feature will make it easier for users to identify the active tab when navigating through a large number of open tabs.

#### Example Implementation

Here's a conceptual example of how to add a hover highlight effect using CSS:

```css
/* Hover highlight effect for active tab */
.Tab.active:hover {
  border-bottom: 2px solid #00BFFF;
  background-color: rgba(0, 191, 255, 0.1);
  transition: background-color 0.3s, border-bottom 0.3s;
}
```

#### Benefits

- Enhances the visual distinction of active tabs.
- Helps users quickly locate and interact with the active tab.
- Adds a subtle but effective UI enhancement to improve usability.
