### ISSUE TITLE
RGB Animation for Text Highlight Color on Webpages

### ISSUE THREAD

**Issue by TanvirOnGH** [TanvirOnGH/firefox-config#75]
## Description

Support for RGB animations within the `::selection` pseudo-element to allow smooth transitions in text highlight colors.

Currently, the highlight color remains static, with no capability to animate color transitions during text selection. The code is (in `userContent.css`):

```css
/* Text Highlight color on webpages */
@-moz-document regexp("http(s)?:.*") {
  ::selection {
    background-color: transparent !important;
    color: #c38f8f !important;
  }
}
```

## Problem

Achieving this effect appears to require JavaScript. Attempts using only CSS haven't worked. Have to explore `userChrome.js`/`userContent.js`.
